# Generated by Django 4.2.3 on 2023-07-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_blog_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
